[project]
name = 'Personal-Training-and-Fitness-Coaching-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.trainer-management]
path = 'contracts/trainer-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
